const express = require("express");
const router = express.Router();
const {login,signup,testJWT,logout} = require("../controllers/controller");
const {validateUserProfile}=require("../validations/userValidation");
const {tokenAuth}= require('../middlewares/tokenAuth');
const {createToken,sessionCheck,sessionDelete}=require("../controllers/user");
const {getMarkets,getProducts} = require("../controllers/buyerController");
router.get("/login/:email/:password", createToken,login);
router.post("/signup", validateUserProfile, signup);
router.get("/testJWT",tokenAuth,sessionCheck,testJWT);
router.get("/logout",tokenAuth,sessionDelete,logout);
router.get("/buyer/market",tokenAuth,sessionCheck,getMarkets);
router.get("/buyer/products/:marketID", tokenAuth,sessionCheck,getProducts);
module.exports = router;