const express = require("express");
const router = express.Router();
const { login,signup,testJWT,logout } = require("../controllers/controller");
const {validateUserProfile}=require("../validations/userValidation");
const {tokenAuth}= require('../middlewares/tokenAuth');
router.get("/login/:email/:password", login);
router.post("/signup", validateUserProfile, signup);
router.get("/testJWT",tokenAuth,testJWT);
router.get("/logout",tokenAuth,logout);
module.exports = router;